version: "3"
services:
  school:
    image: appointmentguru/infrastructure:latest
    volumes:
      - ~/.ssh:/root/.ssh # map ssh keys
      - ./production.environment.yml:/code/ansible/group_vars/server_swarm.yml
      - ./production.docker-compose.yml:/etc/ansible/roles/djangoapp/templates/docker-compose.yml
    command: ansible-playbook /code/ansible/deploy.drf.yml  -i /etc/ansible/inventory/digital_ocean.py -e "organization=appointmentguru service=mediaguru entity_name=media" --skip-tags="kong,postgres"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_LIBRARY=/etc/ansible/library
